language: node_js
node_js:
  - "node"
os: osx
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.8.12
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn test
cache:
  directories:
    - "node_modules"
  yarn: true
